/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

/**
 * Builds the emoji list from Unicode's own `emoji-test.txt`, which is the
 * canonical inventory: every emoji, its name, and the group it belongs to.
 * Nothing here is artwork, so nothing here is licensed artwork: the
 * picker offers characters and the platform draws them.
 *
 * The names are Unicode's English ones. When the picker needs another
 * locale, this generator is the place: CLDR publishes per-locale
 * annotation files with translated names for every emoji, and swapping
 * the name source keeps the rest of the pipeline unchanged.
 *
 * Skin-tone variants are left out. They are more than half of the file and
 * they multiply one gesture into six cells, which is a decision for a
 * later round rather than a reason to make the picker unusable now.
 *
 * Run with the file already downloaded:
 *   curl -s https://www.unicode.org/Public/emoji/latest/emoji-test.txt \
 *     -o /tmp/emoji-test.txt && node scripts/generate-emoji.mjs
 */

import {readFile, writeFile} from 'fs/promises';

const source = await readFile('/tmp/emoji-test.txt', 'utf8');

const groups = [];
const emoji = [];

let group = -1;

for (const line of source.split('\n')) {
	const heading = line.match(/^# group: (.+)$/);

	if (heading) {

		// "Component" holds skin tones and hair styles, which are
		// modifiers rather than things anyone wants to place on a photo.

		if (heading[1] === 'Component') {
			group = -1;
			continue;
		}

		groups.push(heading[1]);
		group = groups.length - 1;
		continue;
	}

	if (group < 0 || !line.includes('; fully-qualified')) {
		continue;
	}

	const entry = line.match(/#\s+(\S+)\s+E\d+\.\d+\s+(.+)$/);

	if (!entry || entry[2].includes('skin tone')) {
		continue;
	}

	emoji.push({c: entry[1], g: group, n: entry[2]});
}

const output = `/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

/**
 * Generated by scripts/generate-emoji.mjs from Unicode's emoji-test.txt.
 * Characters and names, no artwork: the platform draws them.
 */

export const EMOJI_GROUPS = ${JSON.stringify(groups)};

export interface EmojiEntry {

	/**
	 * The character itself, which is the whole payload.
	 */
	c: string;

	/**
	 * Index into EMOJI_GROUPS.
	 */
	g: number;

	/**
	 * Unicode's own name, used as the accessible name, the tooltip and the
	 * search text.
	 */
	n: string;
}

export const EMOJI: EmojiEntry[] = [
${emoji
	.map(
		(entry) =>
			`\t{c: ${JSON.stringify(entry.c)}, g: ${entry.g}, n: ${JSON.stringify(entry.n)}},`
	)
	.join('\n')}
];
`;

await writeFile('src/emojiData.ts', output);

console.log(`${emoji.length} emoji in ${groups.length} groups`);
